// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuyykyapwfxlkwoyteww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eXlreWFwd2Z4bGt3b3l0ZXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjAyMjUsImV4cCI6MjA2NTU5NjIyNX0.7G5ltm3x6ZeGkiBOS_VU7TLo7O6bcZsXIOHTAM44Vvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);